#!/usr/bin/env python3
# Copyright (c) 2026 Open Navigation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate the self-contained world for the RTAB-Map visual loop-closure test.

Why generate one at all: tb3_sandbox ships zero texture images and two
flat-shaded meshes, so a visual feature detector finds almost nothing in it,
and the depot world that does work pulls a 101 MB model from Fuel -- a network
dependency no test in this package currently has.

So the texture here comes from *geometry and colour* rather than image files:
stacks of differently sized, differently shaded boxes give GFTT plenty of
corners while keeping the world a single committed SDF with no external assets.

Deterministic: fixed seed, no randomness at load time.
"""
import random
import sys

ROOM = 4.0          # half-extent of the room, metres
WALL_H = 1.6
SEED = 20260726


def box(name, x, y, z, sx, sy, sz, rgb, static=True):
    r, g, b = rgb
    return f"""    <model name="{name}">
      <static>{'true' if static else 'false'}</static>
      <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="c">
          <geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>
        </collision>
        <visual name="v">
          <geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>
          <material>
            <ambient>{r:.2f} {g:.2f} {b:.2f} 1</ambient>
            <diffuse>{r:.2f} {g:.2f} {b:.2f} 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
      </link>
    </model>
"""


def main():
    rng = random.Random(SEED)
    parts = []

    # Four walls, each a different base shade so headings are distinguishable.
    for i, (nx, ny, shade) in enumerate((
            (1, 0, 0.55), (-1, 0, 0.40), (0, 1, 0.62), (0, -1, 0.33))):
        sx = 0.1 if nx else 2 * ROOM + 0.2
        sy = 0.1 if ny else 2 * ROOM + 0.2
        parts.append(box(f'wall_{i}', nx * ROOM, ny * ROOM, WALL_H / 2,
                         sx, sy, WALL_H, (shade, shade, shade * 0.95)))

    # Crates stacked along the walls.  Varied size, height and shade: every one
    # contributes corners, and no two stretches of wall look alike, which is what
    # stops the loop-closure detector matching the wrong place.
    n = 0
    for nx, ny in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        for k in range(9):
            t = -ROOM + 0.55 + k * (2 * ROOM - 1.1) / 8.0
            along = (t, 0) if ny else (0, t)
            depth = ROOM - 0.35
            cx = nx * depth + along[0]
            cy = ny * depth + along[1]
            stack_z = 0.0
            for _ in range(rng.choice((1, 2, 2, 3))):
                w = rng.uniform(0.28, 0.52)
                d = rng.uniform(0.28, 0.52)
                h = rng.uniform(0.22, 0.40)
                shade = rng.uniform(0.18, 0.92)
                tint = rng.uniform(0.5, 1.0)
                parts.append(box(f'crate_{n}',
                                 cx + rng.uniform(-0.08, 0.08),
                                 cy + rng.uniform(-0.08, 0.08),
                                 stack_z + h / 2, w, d, h,
                                 (shade, shade * tint, shade * rng.uniform(0.5, 1.0))))
                stack_z += h
                n += 1

    # A few free-standing pillars so the middle of the room is not featureless
    # when the camera looks across it.
    for i, (px, py) in enumerate(((2.4, 2.4), (-2.4, 2.4), (2.4, -2.4), (-2.4, -2.4))):
        parts.append(box(f'pillar_{i}', px, py, 0.6, 0.22, 0.22, 1.2,
                         (0.8, 0.35 + 0.15 * i, 0.2)))

    body = ''.join(parts)
    sdf = f"""<?xml version="1.0"?>
<!-- Feature-rich room for the RTAB-Map visual loop-closure system test.

     GENERATED by gen_rtabmap_textured_room.py (seed {SEED}), alongside it.
     Edit that and regenerate rather than hand-editing this file.

     Deliberately built from primitives only: no image textures and no Fuel
     includes, so the test needs no network access and no external assets. The
     visual features RTAB-Map needs come from the corners and shading of {n}
     differently sized and shaded crates lining the four walls, plus four
     pillars. tb3_sandbox is unusable for this, having no texture images at
     all, and the depot world that does work costs a 101 MB Fuel download.

     Room is {2 * ROOM:.0f} x {2 * ROOM:.0f} m, walls {WALL_H} m high.
-->
<sdf version="1.6">
  <world name="rtabmap_textured_room">
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <physics name="3ms" type="ode">
      <max_step_size>0.003</max_step_size>
      <real_time_factor>1</real_time_factor>
    </physics>
    <scene><shadows>0</shadows></scene>

    <light name="sun" type="directional">
      <cast_shadows>0</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.4 0.2 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="c">
          <geometry><plane><normal>0 0 1</normal><size>40 40</size></plane></geometry>
        </collision>
        <visual name="v">
          <geometry><plane><normal>0 0 1</normal><size>40 40</size></plane></geometry>
          <material>
            <ambient>0.5 0.5 0.5 1</ambient>
            <diffuse>0.5 0.5 0.5 1</diffuse>
          </material>
        </visual>
      </link>
    </model>

{body}  </world>
</sdf>
"""
    out = sys.argv[1] if len(sys.argv) > 1 else '/dev/stdout'
    with open(out, 'w') as f:
        f.write(sdf)
    print(f'wrote {out}: {n} crates, room {2 * ROOM:.0f}x{2 * ROOM:.0f} m', file=sys.stderr)


if __name__ == '__main__':
    main()
